run:
  timeout: 5m
  concurrency: 4
  tests: true
  allow-parallel-runners: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocyclo:
    min-complexity: 12

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
          - assign

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
      - experimental
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - exitAfterDefer
      - whyNoLint
      - singleCaseSwitch
      - commentedOutCode
      - appendAssign
      - unnecessaryBlock

  funlen:
    lines: 80
    statements: 40

  lll:
    line-length: 120

  maintidx:
    under: 20

  nlreturn:
    block-size: 2

  cyclop:
    max-complexity: 12
    package-average: 8.0

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true

  goimports:
    local-prefixes: github.com/icoder-new/avito-shop

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - stylecheck
    - bodyclose
    - noctx
    - prealloc
    - cyclop
    - funlen
    - gocognit
    - maintidx
    - nestif
    - gosec
    - dupl
    - goconst
    - gocritic
    - godot
    - misspell
    - whitespace

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - third_party

  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gosec
        - goconst

    - path: _mock\.go
      linters:
        - all

    - path: \.pb\.go
      linters:
        - all

    - source: "^//go:generate "
      linters:
        - lll

    - source: "^//go:make "
      linters:
        - lll

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true